-- Schema for the Online Query System / AI-Assisted Academic Collaboration Platform.
-- Run: mysql -u root -p < sql/schema.sql
CREATE DATABASE IF NOT EXISTS MINI_PROJECT;
USE MINI_PROJECT;

CREATE TABLE IF NOT EXISTS LOGIN (
  EMAIL    VARCHAR(255) PRIMARY KEY,
  PASSWORD VARCHAR(255) NOT NULL            -- bcrypt hash, never plaintext
);

CREATE TABLE IF NOT EXISTS USERLOGIN (
  EMAIL    VARCHAR(255) PRIMARY KEY,
  USERNAME VARCHAR(255),
  PHONE    VARCHAR(20),
  FOREIGN KEY (EMAIL) REFERENCES LOGIN(EMAIL)
);

CREATE TABLE IF NOT EXISTS QUESTION (
  ID             INT AUTO_INCREMENT PRIMARY KEY,
  QUESTION_TITLE VARCHAR(500) NOT NULL,
  BODY           TEXT,
  TAGS           VARCHAR(255),
  AUTHOR_EMAIL   VARCHAR(255),
  CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_tags (TAGS)
);

CREATE TABLE IF NOT EXISTS ANSWER (
  ID             INT AUTO_INCREMENT PRIMARY KEY,
  ANSWER         TEXT NOT NULL,
  QUESTION_TITLE VARCHAR(500),
  AUTHOR_EMAIL   VARCHAR(255),
  CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TAGS (
  ID           INT AUTO_INCREMENT PRIMARY KEY,
  TAGS_NAME    VARCHAR(255) NOT NULL,
  TAGS_CONTENT TEXT
);

CREATE TABLE IF NOT EXISTS ARTICLE (
  ID              INT AUTO_INCREMENT PRIMARY KEY,
  ARTICLE_TITLE   VARCHAR(500) NOT NULL,
  ARTICLE_CONTENT TEXT,
  LINK            VARCHAR(500)
);
